title: Nakasu
description: Description
theme: just-the-docs
url: https://matsumurae.github.io/nakasu

exclude:
    # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    # specific to the theme website:
    - bin/
    - lib/
    - "*.gemspec"
    - "*.gem"
    - LICENSE.txt
    - package.json
    - package-lock.json
    - Rakefile
    - README.md
    # theme test code
    - fixtures/

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Set a path/url to a favicon that will be displayed by the browser
#favicon_ico: "/assets/images/favicon.ico"

# Aux links for the upper right navigation
aux_links:
    "View on GitHub":
        - "//github.com/matsumurae/nakasu"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2023 matsumurae. Distributed by an <a href="https://github.com/matsumurae/nakasu/tree/master/LICENSE.txt">MIT license.</a> <a href="https://pages.github.com/">This site is powered by Github Pages.</a>'

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
    highlight:
        color: yellow
    important:
        title: Important
        color: blue
    new:
        title: New
        color: green
    note:
        title: Note
        color: purple
    warning:
        title: Warning
        color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
    - jekyll-seo-tag

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: false

compress_html:
    clippings: all
    comments: all
    endings: all
    startings: []
    blanklines: false
    profile: false
    # ignore:
    #   envs: all
